# This is a basic workflow to help you get started with Actions

name: Get Docker images from gcr 
env:
  NEW_REGISTRY_URL: "registry.cn-hangzhou.aliyuncs.com"
  NEW_REGISTRY_URL2: "docker.io/skydoor/"

 
on:
  push:
    paths:
      - '.github/workflows/**'

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
        
    ## 解析版本文件生成镜像标签
    ## 上传到阿里云镜像仓库
    ## docker https://github.com/Azure/docker-login
    - name: 获取gcr.io镜像
      run: |
        echo ${{ secrets.MY_ALI_REGISTRY_USERNAME}}
        echo ${{ secrets.MY_ALI_REGISTRY_PASSWD}}
        echo ${NEW_REGISTRY_URL} 
        docker login -u ${{ secrets.MY_ALI_REGISTRY_USER}} -p ${{ secrets.MY_ALI_REGISTRY_PASSWORD}} ${NEW_REGISTRY_URL}
        echo "docker pull from k8s gcr io"
        docker pull k8s.gcr.io/ingress-nginx/controller:v1.1.1@sha256:0bc88eb15f9e7f84e8e56c14fa5735aaa488b840983f87bd79b1054190e660de
        echo "change images tag"
        docker tag k8s.gcr.io/ingress-nginx/controller:v1.1.1@sha256:0bc88eb15f9e7f84e8e56c14fa5735aaa488b840983f87bd79b1054190e660de   registry.cn-hangzhou.aliyuncs.com/foreign_cjt/ingress-nginx/controller:v1.1.1 
        echo "push images to aliyun "
        docker push registry.cn-hangzhou.aliyuncs.com/foreign_cjt/ingress-nginx/controller:v1.1.1
        
        
